In [2]:
# Impot All the necessary library's 


import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\Arpit\\Downloads\\spam.csv")

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
#convert the spam value into numerical form

df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0) 

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
# train our model usin train-test split


from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam, test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [13]:
# convert the text into numerical format


from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59108 stored elements and shape (4457, 7743)>

In [17]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7743))

In [18]:
X_train_cv.shape

(4457, 7743)

In [20]:
v.get_feature_names_out()[7719]

'yrs'

In [23]:
# convert it into array formate


X_train_np =  X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4, 7743))

In [24]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv,y_train)


MultinomialNB()

In [25]:
X_test_cv = v.transform(X_test)

In [28]:
# To evaluate the performance of a classification model

from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       954
           1       0.96      0.89      0.93       161

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [29]:
# Test our model 

emails = [
    '''Dear Valued User,

We are excited to inform you that you have been selected to receive a $1,000 Amazon Gift Card absolutely free! 🎉

To claim your reward, simply click the link below and complete the short survey. It only takes 2 minutes!

👉 Claim Your Gift Now

Hurry! This exclusive offer expires in 24 hours.

Don’t miss out on this incredible opportunity!'''

]
emails_count = v.transform(emails)
model.predict(emails_count)
    

array([1])